-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZgOywyIKsamIjBHJ
RV5T7pA1/pSqqRDk/piZXpOlqLKgCgYIKoZIzj0DAQehRANCAAR4qDLaabqjYpqx
sl5NWbr5PQkNtW8r9198XueTsjcjSXWnIwynoQ1wixVutcBkBsGzthLxCKN8jXdX
NxImuk3C
-----END PRIVATE KEY-----